[package]
name = "fastcdc"
version = "1.0.2"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"
description = "FastCDC (content defined chunking) in pure Rust."
repository = "https://github.com/nlfiedler/fastcdc-rs"
readme = "README.md"
keywords = ["cdc", "chunking"]
license = "MIT"
exclude = [
    "TODO.org",
    "test/*",
]

[build-dependencies]
aes-ctr = "0.3.0"
byteorder = "1.3.1"

[dev-dependencies]
memmap = "0.7.0"
crypto-hash = "0.3.4"
clap = "2.33.0"
